# Generated by Django 5.0.3 on 2024-04-06 08:43

import fitness.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                default="Monday",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="date_of_birth",
            field=models.DateField(validators=[fitness.models.validate_date_of_birth]),
        ),
    ]
